repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args: [--severity=error]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--ignore=E203,W503']

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=88


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        files: (\.tf|\.terraform\.lock\.hcl|\.md)$
      - id: terraform_tflint

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
      - id: go-fmt-repo
      - id: go-revive
      - id: go-revive-mod
      - id: go-revive-repo-mod
      - id: go-mod-tidy
      - id: go-mod-tidy-repo

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.5
    hooks:
      - id: sqlfluff-lint

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        entry: detect-secrets-hook
        exclude: package.lock.json
